name: dbt_sydney_property
version: "1.0.0"
config-version: 2

profile: sydney_property

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  +on_schema_change: "sync_all_columns"

  sydney_property:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +schema: staging
      +materialized: view
      +tags: staging
      +docs:
        node_color: "#FFD700" # yellow
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
      +tags: intermediate
      +docs:
        node_color: "#FFA500" # orange
    reporting:
      +schema: reporting
      +materialized: table
      +tags: reporting
      +docs:
        node_color: "#4169E1" # blue

vars:
  snowplow:context:performance_timing: false
  snowplow:context:useragent: false
